### PR TITLE
Minor grammatical corrections

### PR DESCRIPTION
**Pull request by talatshaikh29**

### CODE REVIEW

**Comment by e0ne** [comment]
Thank you, Takat

**Comment by talatshaikh29** [comment]
Why are you not updating your tutorials?

**Comment by e0ne** [comment]
It's a good question. Probably, I should to start doing it

**Comment by talatshaikh29** [comment]
I just created a simple script that looks asks the user to start a pin based on radio buttons.
screenshot 20

and the pin is then set to high.
screenshot 21

**Comment by talatshaikh29** [comment]
I was thinking maybe I could contribute to your tutorials.

**Comment by e0ne** [comment]
Why not? Feel free to contribute. I'll be on a vacation next two weeks and I'm going to continue to work on this project after it

**Comment by talatshaikh29** [comment]
I have tried to install flaskpi on my Ubuntu 14.04. Need help with the code.

**Pull request merged**
